-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE TABLE IF NOT EXISTS public.events
(
    id bigint NOT NULL,
    type text COLLATE pg_catalog."default" NOT NULL,
    actor json NOT NULL,
    repo json NOT NULL,
    payload json,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT events_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.events
    OWNER to postgres;

GRANT ALL ON TABLE public.events TO anon;

GRANT ALL ON TABLE public.events TO authenticated;

GRANT ALL ON TABLE public.events TO postgres;

GRANT ALL ON TABLE public.events TO service_role;

COMMENT ON TABLE public.events
    IS 'GitHub Events subgraph for my network';
