-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE TABLE IF NOT EXISTS public.repos
(
    id bigint,
    name text COLLATE pg_catalog."default" NOT NULL,
    url text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT repos_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.repos
    OWNER to postgres;

GRANT ALL ON TABLE public.repos TO anon;

GRANT ALL ON TABLE public.repos TO authenticated;

GRANT ALL ON TABLE public.repos TO postgres;

GRANT ALL ON TABLE public.repos TO service_role;

COMMENT ON TABLE public.repos
    IS 'GitHub Repositories subgraph for my network';
